version: 2
jobs:
  build:    
    machine: 
      docker_layer_caching: true
    steps:
      - checkout
      - run: 
          name: Build Image
          command: docker build -t tojanke/check-env:latest .
          no_output_timeout: 2h
      - run:
          name: Log In to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Publish Docker Image to Docker Hub
          command: docker push tojanke/check-env:latest
workflows:
  version: 2
  commit:
    jobs:
      - build      
  update:
    triggers:
      - schedule:
          cron: "0 5 5 1,4,7,10 *"
          filters:
            branches:
              only:
                - master
                
    jobs:
      - build
